services:
  app:
    container_name: springboot-challenge
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      TZ: ${TIMEZONE:-Asia/Kuala_Lumpur}
      VAULT_URL: ${VAULT_URL}
      VAULT_PATH: ${VAULT_PATH}
      VAULT_ROLE_ID: ${VAULT_ROLE_ID}
      VAULT_SECRET_ID: ${VAULT_SECRET_ID}
networks:
  default:
    name: nginx-proxy
    external: true