@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json

### index
GET http://{{host}}/api/v1/attribute?sort=id,desc HTTP/1.1

### show
GET http://{{host}}/api/v1/attribute/22 HTTP/1.1

###
POST http://{{host}}/api/v1/attribute HTTP/1.1
Content-Type: {{contentType}}

{
    "name": "foobarxxx",
    "description": "foobarxxxx"
}

### update

PATCH  http://{{host}}/api/v1/attribute/15 HTTP/1.1
Content-Type: {{contentType}}

{
    "name": "yyy",
    "description": "xxxx"
}

### delete

DELETE  http://{{host}}/api/v1/attribute/14 HTTP/1.1

