@keycloakHost = http://{{$dotenv KC_HOST}}
@keycloakClientId = {{$dotenv KC_CLIENT_BACKEND_ID}}
@keycloakClientSecret = {{$dotenv KC_CLIENT_BACKEND_SECRET}}

@realm = {{$dotenv KC_REALM}}

@host = http://{{$dotenv API_HOST}}
@contentType = application/json
@adminUsername = {{$dotenv KC_TEST_ADMIN}}
@adminPassword = {{$dotenv KC_TEST_ADMIN_PWD}}
@username = {{$dotenv KC_TEST_USER}}
@password = {{$dotenv KC_TEST_USER_PWD}}

###

# @name login
POST {{keycloakHost}}/realms/{{realm}}/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=password
&client_id={{keycloakClientId}}
&client_secret={{keycloakClientSecret}}
&username={{adminUsername}}
&password={{adminPassword}}

### show
GET {{host}}/v1/weather/kuala_lumpur HTTP/1.1
Authorization: Bearer {{login.response.body.access_token}}
