@keycloakHost = http://{{$dotenv KC_HOST}}
@keycloakClientId = {{$dotenv KC_CLIENT_BACKEND_ID}}
@keycloakClientSecret = {{$dotenv KC_CLIENT_BACKEND_SECRET}}

@realm = {{$dotenv KC_REALM}}

@host = http://{{$dotenv API_HOST}}
@contentType = application/json
@adminUsername = {{$dotenv KC_TEST_ADMIN}}
@adminPassword = {{$dotenv KC_TEST_ADMIN_PWD}}
@username = {{$dotenv KC_TEST_USER}}
@password = {{$dotenv KC_TEST_USER_PWD}}

###

# @name login
POST {{keycloakHost}}/realms/{{realm}}/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=password
&client_id={{keycloakClientId}}
&client_secret={{keycloakClientSecret}}
&username={{adminUsername}}
&password={{adminPassword}}

### index
GET {{host}}/v1/attribute HTTP/1.1
Authorization: Bearer {{login.response.body.access_token}}

### index
GET {{host}}/v1/attribute?page=0&size=5&sort=id,desc HTTP/1.1
Authorization: Bearer {{login.response.body.access_token}}

### show
GET {{host}}/v1/attribute/1 HTTP/1.1
Authorization: Bearer {{login.response.body.access_token}}

###
POST {{host}}/v1/attribute HTTP/1.1
Authorization: Bearer {{login.response.body.access_token}}
Content-Type: {{contentType}}

{
    "name": "foobarxxx",
    "description": "foobarxxxx"
}

### update

PATCH  {{host}}/v1/attribute/1 HTTP/1.1
Authorization: Bearer {{login.response.body.access_token}}
Content-Type: {{contentType}}

{
    "name": "yyy",
    "description": "xxxx"
}

### delete

DELETE  {{host}}/v1/attribute/1 HTTP/1.1
Authorization: Bearer {{login.response.body.access_token}}
