@host = http://{{$dotenv API_HOST}}
@contentType = application/json

### index

GET {{host}}/v1/order HTTP/1.1

### show
GET {{host}}/v1/order/13 HTTP/1.1

### array
POST {{host}}/v1/order HTTP/1.1
Content-Type: {{contentType}}

{
    "user_id": 1,
    "products": [
        {
            "product_id": 1,
            "quantity": 2
        }
    ]
}

### update status

PUT  {{host}}/v1/order/status/4 HTTP/1.1
Content-Type: {{contentType}}

{
    "status": "status"
}

### update rating

PUT  {{host}}/v1/order/product-rating/4?rating=2 HTTP/1.1
Content-Type: {{contentType}}

{
    "product_id": 1,
    "rating": 5
}

### delete

DELETE  {{host}}/v1/order/14 HTTP/1.1

